<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php?Principal">AMK</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="index.php?Administrator">Configurações</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<!-- Begin page content -->
<div class="container">

    <div class="page-header">
        <h1>Área Administrativa</h1>
    </div>

    <?php if (SessionHelper::getSession('cad_sucesso')): ?>
        <?php SessionHelper::deleteSession('cad_sucesso'); ?>
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <span class="sr-only">Sucesso:</span>
            Projeto cadastrado com sucesso.
        </div>
    <?php endif; ?>

    <?php if (SessionHelper::getSession('cad_error')): ?>
        <?php SessionHelper::deleteSession('cad_error'); ?>
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            Projeto já existe ou dados invalidos, tente novamente.
        </div>
    <?php endif; ?>

    <p class="lead">Adicione <code>Projetos</code> ao <code>AMK</code> para serem gerenciados.</p>

    <form class="form-inline" id="cadSistema" role="form" action="<?php echo UrlRequestHelper::mountUrlPost('Database', 'salvar'); ?>" method="post">
        <div class="form-group">
            <label for="projeto">Projeto:</label>
            <input type="text" name="projeto" class="form-control" id="projeto" placeholder="Nome do Projeto" required>
        </div>
        <div class="form-group">
            <label for="repositorio">Repositório:</label>
            <input type="text" name="repositorio" class="form-control" id="repositorio" placeholder="Nome do repositório" required>
        </div>
        <div class="form-group">
            <label for="path">Path:</label>
            <input type="text" name="path" class="form-control" id="path" style="width: 36em;" placeholder="Path do repositório" required>
        </div>
        <button type="submit" class="btn btn-primary" id="salvar">Salvar</button>
    </form>
    <br /><br />

    <p class="lead">Projetos gerenciados pelo <code>AMK</code>.</p>

    <?php if ($view_isDatabase): ?>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Projeto</th>
                    <th>Repositorio</th>
                    <th>Path</th>
                    <th>Excluir</th>
                </tr>
            </thead>
            <tbody class="listProjetos">
                <?php foreach ($view_database as $sistema): ?>
                    <tr id="ref_<?php echo $sistema->attributes()->name; ?>">
                        <td><?php echo $sistema->attributes()->name; ?></td>
                        <td><?php echo $sistema->attributes()->repositorio; ?></td>
                        <td><?php echo $sistema->path; ?></td>
                        <td>
                            <button type="button" class="btn btn-danger btn-sm" onclick="excluirProjeto('<?php echo $sistema->attributes()->name; ?>')">
                                <span class="glyphicon glyphicon-remove"></span> Excluir 
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-parent="#accordion">Lista vazia</a>
                    </h4>
                </div>
                <div id="collapse1" class="panel-collapse collapse in">
                    <div class="panel-body"><code>Não existe projetos adicionados ao AMK.</code></div>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <br />

    <p>Retorne a <a href="index.php?Principal">página inicial</a>.</p>
</div>

<footer class="footer">
    <div class="container">
        <p class="text-muted">AMK - Ferramentas de automatização de códigos fonte do Framework PHP MyKing.</p>
    </div>
</footer>