<style>
    #img{
        height: 45px;
        width: 110px;
        margin-top: -10px;
    }
</style>

<div class="navigation-bar fixed-top">

    <div class="navigation-bar-content container">

        <div class="element">
            <a class="text-normal fg-white" href="index.php?Index/logon">
                <div  id="img">
                    <img src="<?php echo PATH_IMAGE_URL; ?>logo2.png"/>
                </div>
            </a>
        </div>

        <span class="element-divider place-right"></span>
        <a class="element place-right" href="index.php?Index/logon"><span class="icon-enter"> <b>Entrar</b></span></a>

        <span class="element-divider place-right"></span>

    </div>
</div>
