<a href="index.php?Principal">
    <!-- Layout c/ imagem -->
<!--    <h1 class="tile-area-title fg-white title-hover">
        <img src="<?php //echo PATH_IMAGE_URL; ?>logo2.png"/>
    </h1>-->

     <!-- Layout s/ imagem -->
    <h1 class="tile-area-title fg-white title-hover">
        <i class="icon-yelp" style="margin-right: 7px;"></i>        
        <?php echo NAME_SIS; ?>
    </h1>
</a>
<div class="user-id">
    <div class="user-id-image">
        <img src="<?php echo $view_url_avatar; ?>" class="shadow">
    </div>
    <div class="user-id-name">
        <span class="first-name"><?php echo $view_first_name; ?></span>
        <span class="last-name"> <?php echo $view_last_name; ?></span>
    </div>
</div>