<div class="grid fluid" style="position: fixed; top: 6%; left: 90%;">
    <div class="row">
        <div class="span12">
            <ul style="position: relative; width: 120px; z-index: 1;min-width: 120px;" class="dropdown-menu open keep-open">
                <li class="menu-title"><i class="icon-plus"></i> Adicionar</li>
                <li><a onclick="adicionarAtributo()" style="padding: 10px 18px !important;" class="fg-lightBlue">Atributo</a></li>
                <li><a onclick="adicionarOneToMany()" style="padding: 10px 18px !important;" class="fg-lightBlue">OneToMany</a></li>
                <li><a onclick="adicionarManyToMany()" style="padding: 10px 18px !important;" class="fg-lightBlue">ManyToMany</a></li>
            </ul>
        </div>
    </div>
</div>

<!--titulo da pagina-->
<h1>
    <a href="javascript:history.go(-1)"><i class="icon-arrow-left-3 fg-darker smaller"></i></a>
    Entity<small class="on-right">Editar ( <?php echo $view_reflection->getNameClass(); ?> )</small>
</h1>

<div class="notice bg-grayLighter">
    <p>Obrigatorio o preenchimento de todos os campos com "<b class="fg-red">*</b>".</p>
</div>
<br />

<form name="fEditar" id="fEditar" action="<?php echo UrlRequestHelper::mountUrlPost('Entity', 'atualizar'); ?>" method="post">

    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Gerar estrutura(s)</h2></div>
        </div>
        <div class="row">
            <div class="span12">
                <div class="input-control checkbox size2" data-role="input-control" >
                    <label>
                        <input name="entity" value='YES' type="checkbox" data-show="intermediate" checked />
                        <span class="check"></span>
                        Entity
                    </label>
                </div>
            </div>
        </div>
    </div>

    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Class ( Nome ) *</h2></div>
        </div>
        <div class="row">
            <div class="span12">
                <div class="input-control text" data-role="input-control">
                    <input type="text" name="objeto" id="objeto" value="<?php echo $view_reflection->getNameClass(); ?>" minlength="3" maxlength="40" required="" placeholder="Digite o nome do objeto" />
                    <button class="btn-clear" tabindex="-1" type="button"></button>
                </div>
            </div>
        </div>
    </div>

    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Conexão</h2></div>
        </div>
        <div class="row">
            <div class="span6">
                <h2>Schema</h2>
                <div class="input-control text" data-role="input-control">
                    <input type="text" name="schema" id="schema" value="<?php echo $view_reflection->getSchema(); ?>" />
                    <button class="btn-clear" tabindex="-1" type="button"></button>
                </div>                
            </div>
            <div class="span6">
                <h2>Tabela <b class="fg-red">*</b></h2>
                <div class="input-control text" data-role="input-control">
                    <input type="text" name="table" id="table" value="<?php echo $view_reflection->getTable(); ?>" required=""/>
                    <button class="btn-clear" tabindex="-1" type="button"></button>
                </div>
            </div>
        </div>
    </div>

    <!-- Temp HTML -->
    <div style="display: none;" id="tmp_html"></div>
    
    <!-- INICIO - ATRIBUTOS -->

    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Propriedades ( Atributos )</h2></div>
        </div>
    </div>

    <div id="listAtributos">

        <?php $colmaps = $view_reflection->getColmaps(); ?>
        <?php if (isset($colmaps[0])): ?>
            <?php foreach ($colmaps as $key => $propriedades): ?>
                <div class="grid fluid tAtributos" style="padding: 10px;background: #F0EEEE; border: 1px solid #E0DDDD;" id="div_atributo_<?php echo $key; ?>">

                    <?php if ($propriedades['atributo'] !== 'id'): ?>
                        <div class="row">
                            <div class="span12">
                                <div class="toolbar transparent link place-right">
                                    <a><button class="bt-frame fg-red deleteButton" style="margin-top: -20px;" onclick="deleteAtributo('div_atributo_<?php echo $key; ?>')"><i class="icon-cancel"></i></button></a>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row">
                        <?php if ($propriedades['atributo'] !== 'id'): ?>
                            <div class="span4">
                                <h2>Atributo <b class="fg-red">*</b></h2>
                                <div class="input-control text" data-role="input-control">
                                    <input type="text" name="dados[<?php echo $key; ?>][atributo]" id="atributo_<?php echo $key; ?>" value="<?php echo $propriedades['atributo']; ?>" required=""/>
                                    <button class="btn-clear" tabindex="-1" type="button"></button>
                                </div>
                            </div>
                        <?php else: ?>
                            <div class="span4">
                                <h2>Atributo <b class="fg-red">*</b></h2>
                                <div class="input-control text" data-role="input-control">
                                    <input type="hidden" name="dados[<?php echo $key; ?>][atributo]" value="<?php echo $propriedades['atributo']; ?>">
                                    <input type="text" value="<?php echo $propriedades['atributo']; ?>" disabled=""/>
                                    <button class="btn-clear" tabindex="-1" type="button"></button>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="span4">
                            <h2>Colmap <b class="fg-red">*</b></h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="dados[<?php echo $key; ?>][colmap]" id="colmap_<?php echo $key; ?>" value="<?php echo $propriedades['colmap']; ?>" required=""/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                        <div class="span4">
                            <h2>OneToOne ( Objeto )</h2>
                            <div class="input-control select">
                                <select name="dados[<?php echo $key; ?>][OneToOne]" id="OneToOne_<?php echo $key; ?>" <?php echo ($propriedades['atributo'] !== 'id') ? '' : 'disabled=""'; ?> >
                                    <?php echo $view_reflection->selectObjectEntity($propriedades['OneToOne']); ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="span2">
                            <h2>Type <b class="fg-red">*</b></h2>
                            <div class="input-control select">
                                <select name="dados[<?php echo $key; ?>][type]" id="type_<?php echo $key; ?>" required="">
                                    <?php echo $view_reflection->selectType($propriedades['type']); ?>
                                </select>
                            </div>
                        </div>
                        <div class="span2">
                            <h2>Mask</h2>
                            <div class="input-control select">
                                <select name="dados[<?php echo $key; ?>][mask]" id="mask_<?php echo $key; ?>">
                                    <?php echo $view_reflection->selectMask($propriedades['mask']); ?>
                                </select>
                            </div>
                        </div>
                        <div class="span2">
                            <h2>NotNull <b class="fg-red">*</b></h2>
                            <div class="input-control select">
                                <select name="dados[<?php echo $key; ?>][NotNull]" id="NotNull_<?php echo $key; ?>">
                                    <?php echo $view_reflection->selectNotNull($propriedades['NotNull']); ?>
                                </select>
                            </div>
                        </div>
                        <div class="span2">
                            <h2>MinSize</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="dados[<?php echo $key; ?>][MinSize]" class='so_numeros' id="MinSize_<?php echo $key; ?>" value="<?php echo $propriedades['MinSize']; ?>" />
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                        <div class="span2">
                            <h2>MaxSize</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="dados[<?php echo $key; ?>][MaxSize]" class='so_numeros' id="MaxSize_<?php echo $key; ?>" value="<?php echo $propriedades['MaxSize']; ?>" />
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                        <div class="span2">
                            <h2>Size</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="dados[<?php echo $key; ?>][size]" class='so_numeros' id="size_<?php echo $key; ?>" value="<?php echo $propriedades['size']; ?>" />
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <?php unset($colmaps); ?>

    </div>
    <!-- FIM - ATRIBUTOS -->

    <!-- INICIO - ManyToOne -->
    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Relacionamento ( OneToMany )</h2></div>
        </div>
    </div>

    <div id="listOneToMany">
        <?php $OneToMany = $view_reflection->getOneToMany(); ?>

        <?php if (isset($OneToMany[0])): ?>

            <?php foreach ($OneToMany as $key => $propriedades): ?>
                <div class="grid fluid tOneToMany" style="padding: 10px;background: #F0EEEE; border: 1px solid #E0DDDD;" id="div_OneToMany_<?php echo $key; ?>">

                    <div class="row">
                        <div class="span12">
                            <div class="toolbar transparent link place-right">
                                <a><button class="bt-frame fg-red deleteButton" style="margin-top: -20px;" onclick="deleteOneToMany('div_OneToMany_<?php echo $key; ?>')"><i class="icon-cancel"></i></button></a>
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="span4">
                            <h2>Atributo <b class="fg-red">*</b></h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="OneToMany[<?php echo $key; ?>][atributo]" id="OneToMany_atributo_<?php echo $key; ?>" value="<?php echo $propriedades['atributo']; ?>" required=""/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                        <div class="span4">
                            <h2>Objeto <b class="fg-red">*</b></h2>
                            <div class="input-control select" data-role="input-control" >
                                <select name="OneToMany[<?php echo $key; ?>][objeto]" id="OneToMany_objeto_<?php echo $key; ?>" required="">
                                    <?php echo $view_reflection->selectObjectEntity($propriedades['objeto']); ?>
                                </select>
                            </div>
                        </div>

                        <div class="span4">
                            <h2>Coluna</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="OneToMany[<?php echo $key; ?>][coluna]" id="OneToMany_coluna_<?php echo $key; ?>" value="<?php echo $propriedades['coluna']; ?>" placeholder="Objeto -> Colmap"/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                    </div>

                </div>
            <?php endforeach; ?>

        <?php else: ?>
            <div class="notice bg-amber" id='noticeOneToMany'>
                <div class="fg-white">
                    <h2>Não existe relacionamentos do tipo OneToMany.</h2>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <!-- FIM - ManyToOne -->


    <!-- INICIO - ManyToMany -->
    <div class="grid fluid">
        <div class="row toolbar_title">
            <div class="span12"><h2 class="subheader-secondary fg-red" style="font-weight: bold;">Relacionamento ( ManyToMany )</h2></div>
        </div>
    </div>

    <div id="listManyToMany">
        <?php $ManyToMany = $view_reflection->getManyToMany(); ?>

        <?php if (isset($ManyToMany[0])): ?>
            <?php foreach ($ManyToMany as $key => $propriedades): ?>
                <div class="grid fluid tManyToMany" style="padding: 10px;background: #F0EEEE; border: 1px solid #E0DDDD;" id="div_ManyToMany_<?php echo $key; ?>">

                    <div class="row">
                        <div class="span12">
                            <div class="toolbar transparent link place-right">
                                <a><button class="bt-frame fg-red deleteButton" style="margin-top: -20px;" onclick="deleteManyToMany('div_ManyToMany_<?php echo $key; ?>')"><i class="icon-cancel"></i></button></a>
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="span4">
                            <h2>Atributo <b class="fg-red">*</b></h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="ManyToMany[<?php echo $key; ?>][atributo]" id="ManyToMany_atributo_<?php echo $key; ?>" value="<?php echo $propriedades['atributo']; ?>" required=""/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                        <div class="span4">
                            <h2>Objeto <b class="fg-red">*</b></h2>
                            <div class="input-control select">
                                <select name="ManyToMany[<?php echo $key; ?>][objeto]" id="ManyToMany_objeto_<?php echo $key; ?>" required="">
                                    <?php echo $view_reflection->selectObjectEntity($propriedades['objeto']); ?>
                                </select>
                            </div>
                        </div>

                        <div class="span4">
                            <h2>Coluna</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="ManyToMany[<?php echo $key; ?>][coluna]" id="ManyToMany_coluna_<?php echo $key; ?>" value="<?php echo $propriedades['coluna']; ?>" placeholder="Objeto -> Colmap"/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                    </div>

                    <div class="row">

                        <div class="span6">
                            <h2>Schema</h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="ManyToMany[<?php echo $key; ?>][schema]" id="ManyToMany_schema_<?php echo $key; ?>" value="<?php echo $propriedades['schema']; ?>" placeholder="Schema do banco de dados"/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                        <div class="span6">
                            <h2>Table <b class="fg-red">*</b></h2>
                            <div class="input-control text" data-role="input-control">
                                <input type="text" name="ManyToMany[<?php echo $key; ?>][table]" id="ManyToMany_table_<?php echo $key; ?>" value="<?php echo $propriedades['table']; ?>" required="" placeholder="Tabela do banco de dados"/>
                                <button class="btn-clear" tabindex="-1" type="button"></button>
                            </div>
                        </div>

                    </div>

                </div>
            <?php endforeach; ?>

        <?php else: ?>
            <div class="notice bg-amber" id='noticeManyToMany'>
                <div class="fg-white">
                    <h2>Não existe relacionamentos do tipo ManyToMany.</h2>
                </div>
            </div><br />
        <?php endif; ?>
    </div>
    <!-- FIM - ManyToMany -->
    <div class="toolbar right-botton-submit">
        <button class="large primary"  id="salvar"><i class="icon-floppy on-left"></i>Salvar</button>
    </div>

</form>