<h1>
    Error<small class="on-right">( Acesso Negado )</small>
</h1>

<div class="grid">
    <div class="row">
        <div class="span2">
            <img src="<?php echo PATH_IMAGE_URL; ?>Ignore-Shield-128.png"/>
        </div>
        <div class="span10">
            <h2>A Requisição da página <strong><?php echo $view_pagina; ?></strong> do módulo <strong><?php echo $view_modulo; ?></strong> não está permitida para o seu usuário.</h2>
            <p>Contate o administrador para liberação dessa funcionalidade.</p>
            <a href="index.php?Principal" class="button large primary">Volte à Principal</a>            
        </div>
    </div>
</div>
